### ISSUE TITLE
How can I add HTTP Headers to requests?

### ISSUE THREAD

**Issue by nicocesar** [fotoetienne/gqai#1]
I found this  server and I wonder if queries with authenticated bearer tokens are possible?

Many GraphQL server have example of something as simple as:

```
curl -i <URL> \
  -H "Authorization: Basic Ym9zY236Ym9zY28=" \
  -H "Authorization: Bearer mytoken123"
```

when making requests.

**Comment by fotoetienne** [comment]
It doesn't handle that yet, but absolutely should.

The plan is to set them via [graphql-config](https://the-guild.dev/graphql/config/docs/user/schema#passing-headers)

```yaml
schema:
  - http://localhost:4000/graphql:
      headers:
        Authorization: "Bearer mytoken123"
```

And optionally using [env vars](https://the-guild.dev/graphql/config/docs/user/schema#environment-variables)

```yaml
schema:
  - http://localhost:4000/graphql:
      headers:
        Authorization: "Bearer ${BEARER_TOKEN}"
```

PR welcome, otherwise I'll add it as soon as I get to it. Thanks for the Issue!
